const woordpakketten = {
    wp2: [
       "gave", 
        "scheve",
        "stijve",
        "de proeven",
        "de golven",
        "de slaven",
        "de schijven",
        "de bedrijven",
        "de olijven",
        "de postduiven",
        "dwaze",
        "wijze",
        "eindeloze",
        "foutloze",
        "werkloze",
        "de bazen",
        "de klokhuizen",
        "de matrozen",
        "de paleizen",
        "de vazen",
    ],
    wp3: [
        "veilig",
        "weinig",
        "eigenwijs",
        "de eigenaar",
        "de aarbei",
        "de reiziger",
        "de reiger",
        "de kapitein",
        "de opleiding",
        "het afscheid",
        "ijverig", 
        "nijdig",
        "tijdens", 
        "tijdelijk", 
        "vlakbij", 
        "de dolfijn", 
        "de woestijn", 
        "de rozijnen", 
        "het ontbijt", 
        "het schilderij", 

        // Voeg meer woorden toe zoals nodig
    ],
    // Voeg meer pakketten toe zoals nodig
};
